version: '3.5'

services:
  postgres:
    container_name: 'postgres'
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    volumes:
      - ./data:/data/postgres
    ports:
      - "5432:5432"