
version: '3.8'

services:
  postgres:
    image: postgres
    container_name: postgres-container
    environment:
      POSTGRES_USER: usuario
      POSTGRES_PASSWORD: senha
      POSTGRES_DB: nome_do_banco
    networks:
      - app-network
    ports:
      - "5432:5432"
    restart: always

  backend:
    container_name: api-nest
    build: .
    environment:
      DATABASE_URL:  postgresql://usuario:senha@postgres-container:5432/nome_do_banco?schema=public
    networks:
      - app-network
    ports:
      - 3000:3000
networks:
  app-network:
    driver: bridge